### ISSUE TITLE
Larger clicking area

### ISSUE THREAD

**Issue by tbyte80** [eFrane/vue-sliding-pagination#236]
Hey, thanks for providing a great pagination component.
It would be awesome if the clickable area would be larger, preferably the whole list node.

**Comment by eFrane** [comment]
You can achieve this either by modifying the CSS or by implementing a custom page component. See https://vue-sliding-pagination.efrane.com/guide.html#customization for more information.

**Comment by eFrane** [comment]
I'll be closing this. Feel free to re-open if you have further questions or if I misinterpreted what you were asking for.
