### ISSUE TITLE
Cannot use "navigation" buttons to navigate forward and back

### ISSUE THREAD

**Issue by Maker-Mark** [eFrane/vue-sliding-pagination#375]
You can see this issue in the demo. https://vue-sliding-pagination.efrane.com/examples.html#very-basic-example
When the forward/back navigation is not disabled, the link is just an href to `#` so you are taken to the top of the page.

This is a very frustrating behavior, and there is no way to override the behavior. 
I attempted to override the slots  `previous-page` and `next-page`  to implement the functionality myself, but those seem to not work. 
Can you provide me with a code sample, or give me permission to contribute so this feature works?

Thank you

**Comment by eFrane** [comment]
Hey @Maker-Mark, thank you for reporting this rather nasty regression. I fixed it and will release a patch version shortly. In general, contributions in the form of PR to this project are very welcome and not restricted at all.

**Comment by eFrane** [comment]
Fixed in v1.3.1.

**Comment by Maker-Mark** [comment]
@eFrane Thank you so much for the quick response and fix! It's surprisingly hard to find a 100% accessible vue paginator. I really appreciate you nipping this one. For the future, is there some basic thing I need to contribute to this, or am I good to just fork and make  a request?

**Comment by eFrane** [comment]
Just fork and PR. If this ever blows up to be unmanagable, I'll likely introduce some hoops to jump through but for now there's no need to overcomplicate things.

**Comment by Maker-Mark** [comment]
@eFrane Sounds good, thanks. Feel free to @ me on a ticket and I'll try to get to it!
